name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: ''

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Run tests
        run: mvn test

      - name: Shut down Docker Compose
        if: always()
        run: docker-compose down