name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Sets up docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push to Docker Hub
        run: |
          docker-compose build
          docker-compose push

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Run tests
        run: mvn test

      - name: Shut down Docker Compose
        if: always()
        run: docker-compose down

      - name: Check for changes in Kubernetes manifests
        id: changes
        run: |
          git diff --exit-code -- k8s-manifests/*.yaml
          echo "changes=true" >> $GITHUB_ENV
          if [[ $? -ne 0 ]]; then
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Create Pull Request for Kubernetes manifest changes
        if: env.changes == 'true'
        run: |
          gh pr create --title "Kubernetes Manifests" \
                        --body "Rodrigo Mendes Kubernetes manifest file." \
                        --base main \
                        --head ${{ github.head_ref }} \
                        --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}