name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Sets up docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push to Docker Hub
        run: |
          docker-compose build
          docker-compose push

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Run tests
        run: mvn test

      - name: Shut down Docker Compose
        if: always()
        run: docker-compose down

      - name: Create Pull Request
        env:
          AUTH_TOKEN: ${{ secrets.GH1_TOKEN }}
        run: |
          curl -X POST "https://api.github.com/repos/apraposo/testing/pulls" \
          -H "Authorization: token $AUTH_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{
            "title": ">Rodrigo Mendes k8s-manifest.yaml",
            "body": "Rodrigo Mendes Kubernetes manifest file for deployment.",
            "head": "rlmcmendes:main",
            "base": "main"
          }'