name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Sets up docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push to Docker Hub
        run: |
          docker-compose build
          docker-compose push

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Run tests
        run: mvn test

      - name: Shut down Docker Compose
        if: always()
        run: docker-compose down

      - name: Create a new branch
        run: git checkout -b k8s-manifest-update

      - name: Copy k8s-manifest file
        run: |
          ls
          cp k8s-manifest.yaml ./k8s-manifest.yaml

      - name: Commit changes
        run: |
          git add ./k8s-manifest.yaml
          git commit -m "Add k8s-manifest file"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH1_TOKEN }}
        run: |
          git remote add upstream https://github.com/apraposo/testing.git
          git push -u upstream k8s-manifest-update

      - name: Create Pull Request using cURL
        env:
          GITHUB_TOKEN: ${{ secrets.GH1_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/apraposo/testing/pulls \
          -d '{
            "title": "Add k8s-manifest",
            "head": "k8s-manifest-update",
            "base": "main",
            "body": "This PR adds the k8s-manifest file."
          }'